<?php

namespace App\Support\QcTemplates\Presets;

use App\Support\QcTemplates\PresetBlocks;

class RawMillMaagGearInnerPartGearBox16Template
{
    public static function data(): array
    {
        $meta = [
            'equipment' => 'Maag Gear WPU-302',
            'pekerjaan' => 'Inspeksi Inner Part Gear Box',
        ];

        $rows = [
            [
                'no' => 1,
                'komponen' => 'Fitted Bolts',
                'parameter' => 'LP 1',
                'lp_point' => '1',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 1,
                'komponen' => 'Fitted Bolts',
                'parameter' => 'LP 2',
                'lp_point' => '2',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 1,
                'komponen' => 'Fitted Bolts',
                'parameter' => 'LP 3',
                'lp_point' => '3',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 1,
                'komponen' => 'Fitted Bolts',
                'parameter' => 'LP 4',
                'lp_point' => '4',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 1,
                'komponen' => 'Fitted Bolts',
                'parameter' => 'LP 5',
                'lp_point' => '5',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 1,
                'komponen' => 'Fitted Bolts',
                'parameter' => 'LP 6',
                'lp_point' => '6',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 1,
                'komponen' => 'Fitted Bolts',
                'parameter' => 'LP 7',
                'lp_point' => '7',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 1,
                'komponen' => 'Fitted Bolts',
                'parameter' => 'LP 8',
                'lp_point' => '8',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 1,
                'komponen' => 'Fitted Bolts',
                'parameter' => 'LP 9',
                'lp_point' => '9',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 1,
                'komponen' => 'Fitted Bolts',
                'parameter' => 'LP 10',
                'lp_point' => '10',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 1,
                'komponen' => 'Fitted Bolts',
                'parameter' => 'LP 11',
                'lp_point' => '11',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 1,
                'komponen' => 'Fitted Bolts',
                'parameter' => 'LP 12',
                'lp_point' => '12',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],

            [
                'no' => 2,
                'komponen' => 'Bearing Parts',
                'parameter' => 'B',
                'lp_point' => '1',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 2,
                'komponen' => 'Bearing Parts',
                'parameter' => 'B',
                'lp_point' => '2',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 2,
                'komponen' => 'Bearing Parts',
                'parameter' => 'B',
                'lp_point' => '3',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 2,
                'komponen' => 'Bearing Parts',
                'parameter' => 'C',
                'lp_point' => '1',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 2,
                'komponen' => 'Bearing Parts',
                'parameter' => 'C',
                'lp_point' => '2',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 2,
                'komponen' => 'Bearing Parts',
                'parameter' => 'C',
                'lp_point' => '3',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],

            [
                'no' => 3,
                'komponen' => 'Bearing Shield',
                'parameter' => 'A',
                'lp_point' => '1',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => 'For bearing No.4',
            ],
            [
                'no' => 3,
                'komponen' => 'Bearing Shield',
                'parameter' => 'A',
                'lp_point' => '2',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => 'For bearing No.4',
            ],
            [
                'no' => 3,
                'komponen' => 'Bearing Shield',
                'parameter' => 'A',
                'lp_point' => '3',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => 'For bearing No.4',
            ],
            [
                'no' => 3,
                'komponen' => 'Bearing Shield',
                'parameter' => 'B',
                'lp_point' => '1',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => 'For bearing No.4',
            ],
            [
                'no' => 3,
                'komponen' => 'Bearing Shield',
                'parameter' => 'B',
                'lp_point' => '2',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => 'For bearing No.4',
            ],
            [
                'no' => 3,
                'komponen' => 'Bearing Shield',
                'parameter' => 'B',
                'lp_point' => '3',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => 'For bearing No.4',
            ],
            [
                'no' => 3,
                'komponen' => 'Bearing Shield',
                'parameter' => 'C',
                'lp_point' => '1',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => 'For bearing No.4',
            ],
            [
                'no' => 3,
                'komponen' => 'Bearing Shield',
                'parameter' => 'C',
                'lp_point' => '2',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => 'For bearing No.4',
            ],
            [
                'no' => 3,
                'komponen' => 'Bearing Shield',
                'parameter' => 'C',
                'lp_point' => '3',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => 'For bearing No.4',
            ],

            [
                'no' => 4,
                'komponen' => 'Bearing Cover',
                'parameter' => 'A',
                'lp_point' => '1',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 4,
                'komponen' => 'Bearing Cover',
                'parameter' => 'A',
                'lp_point' => '2',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 4,
                'komponen' => 'Bearing Cover',
                'parameter' => 'A',
                'lp_point' => '3',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 4,
                'komponen' => 'Bearing Cover',
                'parameter' => 'B',
                'lp_point' => '1',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 4,
                'komponen' => 'Bearing Cover',
                'parameter' => 'B',
                'lp_point' => '2',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 4,
                'komponen' => 'Bearing Cover',
                'parameter' => 'B',
                'lp_point' => '3',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 4,
                'komponen' => 'Bearing Cover',
                'parameter' => 'C',
                'lp_point' => '1',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 4,
                'komponen' => 'Bearing Cover',
                'parameter' => 'C',
                'lp_point' => '2',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 4,
                'komponen' => 'Bearing Cover',
                'parameter' => 'C',
                'lp_point' => '3',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],

            [
                'no' => 5,
                'komponen' => 'Housing for Bearing Bush',
                'parameter' => 'LP 1',
                'lp_point' => '1',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 5,
                'komponen' => 'Housing for Bearing Bush',
                'parameter' => 'LP 2',
                'lp_point' => '2',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 5,
                'komponen' => 'Housing for Bearing Bush',
                'parameter' => 'LP 3',
                'lp_point' => '3',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],

            [
                'no' => 6,
                'komponen' => 'Bearing Bush',
                'parameter' => 'LP 1',
                'lp_point' => '1',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 6,
                'komponen' => 'Bearing Bush',
                'parameter' => 'LP 2',
                'lp_point' => '2',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 6,
                'komponen' => 'Bearing Bush',
                'parameter' => 'LP 3',
                'lp_point' => '3',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],

            [
                'no' => 7,
                'komponen' => 'Interfence for Bearing No.1 dan 2',
                'parameter' => 'LP 1',
                'lp_point' => '1',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 7,
                'komponen' => 'Interfence for Bearing No.1 dan 2',
                'parameter' => 'LP 2',
                'lp_point' => '2',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 7,
                'komponen' => 'Interfence for Bearing No.1 dan 2',
                'parameter' => 'LP 3',
                'lp_point' => '3',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],

            [
                'no' => 8,
                'komponen' => 'Thrust Pad',
                'parameter' => 'Thrust Pad 1',
                'lp_point' => '1',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 8,
                'komponen' => 'Thrust Pad',
                'parameter' => 'Thrust Pad 2',
                'lp_point' => '2',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 8,
                'komponen' => 'Thrust Pad',
                'parameter' => 'Thrust Pad 3',
                'lp_point' => '3',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 8,
                'komponen' => 'Thrust Pad',
                'parameter' => 'Thrust Pad 4',
                'lp_point' => '4',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 8,
                'komponen' => 'Thrust Pad',
                'parameter' => 'Thrust Pad 5',
                'lp_point' => '5',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 8,
                'komponen' => 'Thrust Pad',
                'parameter' => 'Thrust Pad 6',
                'lp_point' => '6',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 8,
                'komponen' => 'Thrust Pad',
                'parameter' => 'Thrust Pad 7',
                'lp_point' => '7',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 8,
                'komponen' => 'Thrust Pad',
                'parameter' => 'Thrust Pad 8',
                'lp_point' => '8',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 8,
                'komponen' => 'Thrust Pad',
                'parameter' => 'Thrust Pad 9',
                'lp_point' => '9',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 8,
                'komponen' => 'Thrust Pad',
                'parameter' => 'Thrust Pad 10',
                'lp_point' => '10',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 8,
                'komponen' => 'Thrust Pad',
                'parameter' => 'Thrust Pad 11',
                'lp_point' => '11',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 8,
                'komponen' => 'Thrust Pad',
                'parameter' => 'Thrust Pad 12',
                'lp_point' => '12',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 8,
                'komponen' => 'Thrust Pad',
                'parameter' => 'Thrust Pad 13',
                'lp_point' => '13',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 8,
                'komponen' => 'Thrust Pad',
                'parameter' => 'Thrust Pad 14',
                'lp_point' => '14',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
            [
                'no' => 8,
                'komponen' => 'Thrust Pad',
                'parameter' => 'Thrust Pad 15',
                'lp_point' => '15',
                'a' => '',
                'b' => '',
                'c' => '',
                'measurement' => '',
                'standard' => '',
                'status' => '',
                'keterangan' => '',
            ],
        ];

        $blocks = PresetBlocks::make($meta, [], [
            'attachment' => [
                'title' => 'Lampiran Foto / Drawing',
                'description' => 'Upload foto part, drawing, hasil pengukuran, dan dokumen pendukung.',
                'fields' => [
                    [
                        'key' => 'foto_part',
                        'label' => 'Foto Part',
                        'type' => 'image',
                        'accept' => 'image/*',
                        'multiple' => true,
                        'required' => true,
                        'max_files' => 10,
                    ],
                    [
                        'key' => 'foto_drawing',
                        'label' => 'Foto Drawing',
                        'type' => 'image',
                        'accept' => 'image/*',
                        'multiple' => true,
                        'required' => false,
                        'max_files' => 10,
                    ],
                    [
                        'key' => 'dokumen_pendukung',
                        'label' => 'Dokumen Pendukung',
                        'type' => 'file',
                        'accept' => '.pdf,.doc,.docx,.xls,.xlsx,image/*',
                        'multiple' => true,
                        'required' => false,
                        'max_files' => 5,
                    ],
                ],
            ],
            'approval' => [
                'title' => 'Approval',
                'columns' => [
                    [
                        'key' => 'diperiksa_1',
                        'label' => 'Diperiksa Oleh',
                        'type' => 'signature',
                    ],
                    [
                        'key' => 'diperiksa_2',
                        'label' => 'Diperiksa Oleh',
                        'type' => 'signature_locked',
                    ],
                ],
                'notes' => [
                    'Diperiksa oleh QC / inspector pekerjaan.',
                    'Diperiksa oleh supervisor atau pihak terkait.',
                ],
            ],
        ]);

        foreach ($blocks as $index => $block) {
            if (($block['type'] ?? null) === 'checklist_table') {
                $blocks[$index] = [
                    'type' => 'measurement_table',
                    'title' => 'Pengukuran Inner Part Gear Box WPU-302',
                    'description' => 'Checklist Inner Part Gear Box WPU-302 Raw Mill 532 RM 01 - MAAG Gear.',
                    'columns' => [
                        [
                            'key' => 'no',
                            'label' => 'No',
                            'type' => 'number',
                            'readonly' => true,
                        ],
                        [
                            'key' => 'komponen',
                            'label' => 'Komponen',
                            'type' => 'textarea',
                            'readonly' => true,
                        ],
                        [
                            'key' => 'parameter',
                            'label' => 'Parameter',
                            'type' => 'text',
                            'readonly' => true,
                        ],
                        [
                            'key' => 'lp_point',
                            'label' => 'LP / Point',
                            'type' => 'text',
                            'readonly' => true,
                        ],
                        [
                            'key' => 'a',
                            'label' => 'A',
                            'type' => 'text',
                            'readonly' => false,
                        ],
                        [
                            'key' => 'b',
                            'label' => 'B',
                            'type' => 'text',
                            'readonly' => false,
                        ],
                        [
                            'key' => 'c',
                            'label' => 'C',
                            'type' => 'text',
                            'readonly' => false,
                        ],
                        [
                            'key' => 'measurement',
                            'label' => 'Measurement',
                            'type' => 'text',
                            'readonly' => false,
                        ],
                        [
                            'key' => 'standard',
                            'label' => 'Standard',
                            'type' => 'text',
                            'readonly' => false,
                        ],
                        [
                            'key' => 'status',
                            'label' => 'Status',
                            'type' => 'text',
                            'readonly' => false,
                        ],
                        [
                            'key' => 'keterangan',
                            'label' => 'Keterangan',
                            'type' => 'textarea',
                            'readonly' => false,
                        ],
                    ],
                    'rows' => $rows,
                ];

                break;
            }
        }

        return [
            'code' => 'QCR-RM-WPU302-IPGB-016',
            'number' => '16',
            'name' => 'Standard QCR Inspeksi Raw Mill; Maag Gear WPU-302; Inner Part Gear Box',
            'category' => 'Raw Mill',
            'version' => '1.0',
            'status' => 'active',
            'layout_mode' => 'block_based',
            'meta' => $meta,
            'blocks' => $blocks,
        ];
    }
}